### ISSUE TITLE
Clicking Google Places suggestion may not trigger auto-save

### ISSUE THREAD

**Issue by tednyberg** [tedgustaf/episerver-google-maps-editor#1]
If a Google Places suggestion is clicked (instead of selected with Enter key) EPiServer may not trigger the property's auto-save.

**Comment by hesta96** [comment]
I solved it by adding this code to editor.js
onChange: function (value) {
            //This is a chrome fix
            this.parent.save(value);
        },

**Comment by tednyberg** [comment]
Thanks Henrik! Fixed in NuGet package version version 1.0.5.
