### ISSUE TITLE
On-page editing dialog can't be closed.

### ISSUE THREAD

**Issue by HektorW** [tedgustaf/episerver-google-maps-editor#11]
When we were adding the Google maps editor on a local block, we get an error that is making the dialog impossible to close with the upper right close icon.

Steps to reproduce:
* Create a block that uses the Google maps editor
* Add the block as a local block on a page type
* Edit using on-page editing. The edit dialog can't be closed with the upper right close button.

I've found that the problem can be avoided by checking if `this.parent` has a valid value before using it in the `onChange` function in `Editor.js`. It seems that `this.parent` is undefined when `onChange` is first invoked.

Changing `onChange` to the following fixes the issue for me:
```
onChange: function(value) {
    console.log('onchange');
    if (this.parent) {
        this.parent.save(value);
    }
}
```
With this code the dialog can be closed as expected.

I'm not sure if this is a correct way of solving the problem though, since I don't have any experience developing dojo widgets.

**Comment by tednyberg** [comment]
Thanks for reporting it! We will have a look at it.

**Comment by tednyberg** [comment]
Unable to reproduce as of 1.0.5.
