### ISSUE TITLE
Editor doesn't show existing value, Episerver update 92 (9.4)

### ISSUE THREAD

**Issue by pellebjerkestrand** [tedgustaf/episerver-google-maps-editor#14]
After specifying a location and saving a page that has this editor on it, the editor does not show the saved value when entering edit mode again.

**Comment by shinpou** [comment]
This appears to be a problem in the latest Episerver, where it appears that the order in which the constructor events fire is now different (maybe a bug, not sure). The "startup" and therefore the InitializeMap function is called before episerver calls _setValueAttr for the widget, and thus the value isn't available in the initialization function. To make it work with the new order, it would have to run the initialization code only after both _setValueAttr and _setReadOnlyAttr have been called, but it is not entirely a trivial change to make.

**Comment by shinpou** [comment]
I have made a ticket to Episerver about this: will keep you posted on what happens.

**Comment by shinpou** [comment]
This has been confirmed and reproduced by episerver as a bug in their end. Will post bug number when I have it.

**Comment by ben-mckernan** [comment]
I have investigated and this isn't an episerver bug. Editor widgets can have their values set at any time and it should not be expected that the value is available before startup in all cases. A good example of this is compare mode where it is possible to copy the old value to the current version. A quick test on an older version (EPiServer.CMS.UI 9.0.0) shows that the map editor does not work in this case.

**Comment by BrayanA** [comment]
I'm with latest version of EPiServer and the editor still does not show the saved value when entering edit mode again even with ben-mckernan changes.

**Comment by BrayanA** [comment]
Hmmmm ... looks like the solution was quite simple. Indeed EPiServer is not calling _setValueAttr for the widget. But if you add 'value' declaration like this:
return declare([_Widget, _TemplatedMixin, _WidgetsInTemplateMixin, _ValueRequiredMixin], {
        value: null, 

        // The Google Maps object of this widget instance
        map: null,
        ...

It now works correctly and _setValueAttr is called. BTW I'm working with ben-mckernan version.
