### ISSUE TITLE
Unable to config api key

### ISSUE THREAD

**Issue by mathiasnohall** [tedgustaf/episerver-google-maps-editor#19]
Is there a way to config a google maps api key?

like: https://maps.google.com/maps/api/js?key=API_KEY_HERE

**Comment by tednyberg** [comment]
The add-on was created before Google introduced the API key requirement, but you can easily add an API key to the Google Maps URL in the Editor.js file, where the dependencies are declared.

Just add `&key=[YOUR API KEY]` after the dependency:
`tedgustaf/googlemaps/Async!https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=xyz123`

**Comment by mathiasnohall** [comment]
thats true! Thx! Would be nice though in a future version to make this configurable.

Future updates via nuget would overwrite that hack in the source code.

Regards

**Comment by tednyberg** [comment]
An API key will be included by default starting with version 1.0.7.
